In [1]:
import numpy as np

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [3]:
#sumowanie całości
price.sum()

4650.1

In [4]:
price.sum(axis=0) #sumowanie po kolumnach

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis=1) #sumowanie po wierszach

array([1049.7, 2049.4, 1551. ])

In [7]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

min()

In [8]:
np.min(price) #minimum z całej tablicy

11.7

In [9]:
np.min(price, axis=0) #minimum z kolumny

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [10]:
np.min(price, axis=1) #minimum z wiersza

array([11.9, 11.7, 12.2])