In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [8]:
x = np.array([1, 3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
#wymiar tablicy
x.ndim

1

In [13]:
#kształt tablicy, 2 elemn
x.shape

(2,)

In [14]:
x.size

2

In [15]:
x.dtype

dtype('int32')

In [18]:
x= np.array(([1.3,2.3,1.4]))
x

array([1.3, 2.3, 1.4])

In [20]:
x.dtype

dtype('float64')

2D Array

In [22]:
x = np.array([[1,2],[-3,1]])

In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [25]:
x.size

4

In [26]:
x = np.array([[1,2,4],[4,2,1]])

In [27]:
x.shape #wymiar 2x3 - dwa wiersze i 3 kolumny

(2, 3)

3D Array

In [31]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
      
      [[4,1,3],
      [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [33]:
x.ndim

3

In [34]:
x.shape #2 tablice, skladajace sie z 2 wierszy i 3 kolumn

(2, 2, 3)

TYPY DANYCH

In [3]:
A = np.array([1,2,3])
A.dtype

dtype('int32')

In [4]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [6]:
A = np.array([1,2,3], dtype='complex')

A.dtype

dtype('complex128')

In [7]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
A = np.array([1,0,-5], dtype='bool')
A

array([ True, False,  True])

TWORZENIE TABLIC

In [14]:
np.zeros(shape=(4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full(shape=(3,3),fill_value=4,dtype=int)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [21]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
np.arange(start=100,stop=-100,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0, -10, -20,
       -30, -40, -50, -60, -70, -80, -90])

In [25]:
np.linspace(start=0,stop=1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
A.reshape((5,3)) #zmiana rozmiaru tablicy

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
A.reshape((3,-1)) #automatyczne obliczanie liczby kolumn przy np 3 wierszach

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
A.reshape((-1,3)) #automatyczne obliczanie liczby wierszy przy np 3 kolumnach

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

PODSTAWOWE OPERACJE NA TABLICACH

In [32]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

In [39]:
#dodawanie tablic

#sposób 1:
A+B

#sposób 2
np.add(A,B)

array([6, 0, 7, 4])

In [41]:
#dodejmowanie tablic

#sposób 1:
A-B

#sposób 2
np.subtract(A,B)

array([0, 2, 1, 0])

In [43]:
#mnożenie tablic

#sposób 1:
A*B

#sposób 2
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [49]:
#dzielenietablic

#sposób 1:
A/B

#sposób 2
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [37]:
A+3

array([6, 4, 7, 5])

In [38]:
2 * A

array([6, 2, 8, 4])

In [45]:
A + 3*B

array([12, -2, 13,  8])

In [54]:
#mnożenie macierzy
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])

np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [51]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [52]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [55]:
X @ Y

array([[  3,   6],
       [-12,   0]])

GENEROWANIE LICZB PSEUDOLOSOWYCH

In [3]:
#ustawienie ziarna losowania
np.random.seed(10)

In [77]:
np.random.randn(10)

array([ 0.31935642,  0.4609029 , -0.21578989,  0.98907246,  0.31475378,
        2.46765106, -1.50832149,  0.62060066, -1.04513254, -0.79800882])

In [78]:
np.random.randn(10,4)

array([[ 1.98508459,  1.74481415, -1.85618548, -0.2227737 ],
       [-0.06584785, -2.13171211, -0.04883051,  0.39334122],
       [ 0.21726515, -1.99439377,  1.10770823,  0.24454398],
       [-0.06191203, -0.75389296,  0.71195902,  0.91826915],
       [-0.48209314,  0.08958761,  0.82699862, -1.95451212],
       [ 0.11747566, -1.90745689, -0.92290926,  0.46975143],
       [-0.14436676, -0.40013835, -0.29598385,  0.84820861],
       [ 0.70683045, -0.78726893,  0.29294072, -0.47080725],
       [ 2.40432561, -0.73935674, -0.31282876, -0.34888192],
       [-0.43902624,  0.14110417,  0.27304932, -1.61857075]])

In [84]:
np.random.rand(5,2)

array([[0.84876407, 0.74267458],
       [0.45669754, 0.41689841],
       [0.11672951, 0.33867913],
       [0.09465904, 0.71583087],
       [0.0770854 , 0.20595026]])

In [90]:
np.random.randint(10)

5

In [91]:
np.random.randint(low=10,high=101)

89

In [92]:
np.random.randint(low=10,high=101, size=10)

array([69, 30, 41, 99, 10, 35, 73, 69, 12, 40])

In [95]:
np.random.choice([4,3,2,6,4,2])

2

In [96]:
np.random.choice(['python','java','sql'])

'sql'

In [98]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.random.shuffle(data)

In [100]:
data

array([4, 6, 9, 5, 2, 8, 0, 1, 3, 7])

PODSTAWOWE FUNKCJE

In [101]:
np.exp(1)

2.718281828459045

In [102]:
np.sqrt(4)

2.0

In [105]:
np.all([2,3,1])

True

In [106]:
np.any([1,2,1])

True

In [5]:
A = np.random.rand(5)
A

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [6]:
A[np.argmax(A)]

0.771320643266746

In [10]:
A[np.argmax(A)]

0.771320643266746

In [11]:
np.argmin(A)

1

In [12]:
A[np.argmin(A)]

0.0207519493594015

In [13]:
np.argsort(A) #zwraca indeksy

array([1, 4, 2, 3, 0], dtype=int64)

In [14]:
np.max(A)

0.771320643266746

In [15]:
np.min(A)

0.0207519493594015

In [16]:
np.mean(A)

0.534606344478725

In [17]:
np.median(A)

0.6336482349262754

In [20]:
A.mean()

0.534606344478725

In [21]:
np.std(A)

0.2746172033183844

INDEKSOWANIE, WYCINANIE

In [23]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[index], A[start:stop], A[:stop], A[start:]

In [24]:
A[2]

2

In [25]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
A[:2]

array([0, 1])

In [28]:
A[[0,2]]
  

array([0, 2])

In [29]:
A[-1]

19

In [30]:
A[10:15]

array([10, 11, 12, 13, 14])

In [33]:
A = A.reshape(4,5)

In [34]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
#wycinanie wierszy
A[0]

array([0, 1, 2, 3, 4])

In [36]:
A[3]

array([15, 16, 17, 18, 19])

In [38]:
#wycinanie kolumny
A[:,3]

array([ 3,  8, 13, 18])

In [39]:
#wycinanie elementu
A[1,1]

6

In [41]:
#wycinanie fragmentu tablicy
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [42]:
A[1,2] = 14

In [43]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

ITERACJA PO TABLICACH

In [44]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [47]:
for row in A:
    print(row[0])

0
5
10
15


In [56]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


ZMIANA ROZMIARU TABLIC

In [57]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [61]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
A.T #transpozycja

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [71]:
#MASKI LOGICZNE

In [81]:
A = np.arange(start=-10,stop=10,step=0.5)
A = A.reshape(10,-1)

In [84]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [85]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [86]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [89]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [93]:
help(np.bincount)

Help on _ArrayFunctionDispatcher in module numpy:

bincount(...)
    bincount(x, /, weights=None, minlength=0)
    
    Count number of occurrences of each value in array of non-negative ints.
    
    The number of bins (of size 1) is one larger than the largest value in
    `x`. If `minlength` is specified, there will be at least this number
    of bins in the output array (though it will be longer if necessary,
    depending on the contents of `x`).
    Each bin gives the number of occurrences of its index value in `x`.
    If `weights` is specified the input array is weighted by it, i.e. if a
    value ``n`` is found at position ``i``, ``out[n] += weight[i]`` instead
    of ``out[n] += 1``.
    
    Parameters
    ----------
    x : array_like, 1 dimension, nonnegative ints
        Input array.
    weights : array_like, optional
        Weights, array of the same shape as `x`.
    minlength : int, optional
        A minimum number of bins for the output array.
    
        .. versi