In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [8]:
x = np.array([1, 3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
#wymiar tablicy
x.ndim

1

In [13]:
#kształt tablicy, 2 elemn
x.shape

(2,)

In [14]:
x.size

2

In [15]:
x.dtype

dtype('int32')

In [18]:
x= np.array(([1.3,2.3,1.4]))
x

array([1.3, 2.3, 1.4])

In [20]:
x.dtype

dtype('float64')

2D Array

In [22]:
x = np.array([[1,2],[-3,1]])

In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [25]:
x.size

4

In [26]:
x = np.array([[1,2,4],[4,2,1]])

In [27]:
x.shape #wymiar 2x3 - dwa wiersze i 3 kolumny

(2, 3)

3D Array

In [31]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
      
      [[4,1,3],
      [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [33]:
x.ndim

3

In [34]:
x.shape #2 tablice, skladajace sie z 2 wierszy i 3 kolumn

(2, 2, 3)

TYPY DANYCH

In [3]:
A = np.array([1,2,3])
A.dtype

dtype('int32')

In [4]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [6]:
A = np.array([1,2,3], dtype='complex')

A.dtype

dtype('complex128')

In [7]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
A = np.array([1,0,-5], dtype='bool')
A

array([ True, False,  True])

TWORZENIE TABLIC

In [14]:
np.zeros(shape=(4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full(shape=(3,3),fill_value=4,dtype=int)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [21]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
np.arange(start=100,stop=-100,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0, -10, -20,
       -30, -40, -50, -60, -70, -80, -90])

In [25]:
np.linspace(start=0,stop=1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
A.reshape((5,3)) #zmiana rozmiaru tablicy

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
A.reshape((3,-1)) #automatyczne obliczanie liczby kolumn przy np 3 wierszach

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
A.reshape((-1,3)) #automatyczne obliczanie liczby wierszy przy np 3 kolumnach

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

PODSTAWOWE OPERACJE NA TABLICACH

In [32]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

In [39]:
#dodawanie tablic

#sposób 1:
A+B

#sposób 2
np.add(A,B)

array([6, 0, 7, 4])

In [41]:
#dodejmowanie tablic

#sposób 1:
A-B

#sposób 2
np.subtract(A,B)

array([0, 2, 1, 0])

In [43]:
#mnożenie tablic

#sposób 1:
A*B

#sposób 2
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [49]:
#dzielenietablic

#sposób 1:
A/B

#sposób 2
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [37]:
A+3

array([6, 4, 7, 5])

In [38]:
2 * A

array([6, 2, 8, 4])

In [45]:
A + 3*B

array([12, -2, 13,  8])

In [54]:
#mnożenie macierzy
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])

np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [51]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [52]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [55]:
X @ Y

array([[  3,   6],
       [-12,   0]])