In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [8]:
x = np.array([1, 3])
x

array([1, 3])

In [9]:
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
#wymiar tablicy
x.ndim

1

In [13]:
#kształt tablicy, 2 elemn
x.shape

(2,)

In [14]:
x.size

2

In [15]:
x.dtype

dtype('int32')

In [18]:
x= np.array(([1.3,2.3,1.4]))
x

array([1.3, 2.3, 1.4])

In [20]:
x.dtype

dtype('float64')

2D Array

In [22]:
x = np.array([[1,2],[-3,1]])

In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [25]:
x.size

4

In [26]:
x = np.array([[1,2,4],[4,2,1]])

In [27]:
x.shape #wymiar 2x3 - dwa wiersze i 3 kolumny

(2, 3)

3D Array

In [31]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
      
      [[4,1,3],
      [4,2,1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [33]:
x.ndim

3

In [34]:
x.shape #2 tablice, skladajace sie z 2 wierszy i 3 kolumn

(2, 2, 3)

TYPY DANYCH

In [3]:
A = np.array([1,2,3])
A.dtype

dtype('int32')

In [4]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [6]:
A = np.array([1,2,3], dtype='complex')

A.dtype

dtype('complex128')

In [7]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
A = np.array([1,0,-5], dtype='bool')
A

array([ True, False,  True])

TWORZENIE TABLIC

In [14]:
np.zeros(shape=(4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])